# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'vs2017-win2016'
      demands:
      - msbuild
      - visualstudio
      - vstest
      - java

    variables:
      solution: '**/*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'

    steps:
    - task: NuGetToolInstaller@0
      displayName: 'Use NuGet 4.3.0'
      inputs:
        versionSpec: 4.3.0

    - task: NuGetCommand@2
      displayName: 'NuGet restore'
      inputs:
        restoreSolution: '$(solution)'
  
    - task: SonarCloudPrepare@1
      displayName: 'Prepare analysis on SonarCloud'
      inputs:
        SonarCloud: 'narayana-sonarcloudanalysis'
        organization: 'rubdevopson'
        scannerMode: 'MSBuild'
        projectKey: 'rubdevopson_Selenium'
        projectName: 'Selenium'
    
    - task: VSBuild@1
      displayName: 'Build solution'
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)\\"'
        platform: '$(BuildPlatform)'
        configuration: '$(BuildConfiguration)'
    
    - task: VSTest@2
      displayName: 'Test Assemblies'
      inputs:
        testSelector: 'testAssemblies'
        testAssemblyVer2: |
          **\$(BuildConfiguration)\*test*.dll
          !**\obj\**
        searchFolder: '$(System.DefaultWorkingDirectory)'
        codeCoverageEnabled: true
        platform: '$(BuildPlatform)'
        configuration: '$(BuildConfiguration)'
        diagnosticsEnabled: true
    
    - task: CopyFiles@2
      displayName: 'Copy Selenium Tests'
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/test/PartsUnlimited.SeleniumTests/bin/$(BuildConfiguration)'
        Contents: '**'
        TargetFolder: '$(build.artifactstagingdirectory)/TestAssemblies'
      
    - task: CopyFiles@2
      displayName: 'Copy Database Files'
      inputs:
        SourceFolder: 'Database/Database'
        Contents: '**'
        TargetFolder: '$(build.artifactstagingdirectory)/Database'
    
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Deploy
  displayName: Deploy
  jobs:
  - deployment: deploymentjob
    displayName: Deployment Job
    environment:
      name: narayanaplayenvironment
      resourceName: seleniumvm
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
            - task: DownloadBuildArtifacts@0
              inputs:
                buildType: 'current'
                downloadType: 'single'
                artifactName: 'drop'
                downloadPath: '$(System.ArtifactsDirectory)'
            
            - task: IISWebAppManagementOnMachineGroup@0
              inputs:
                IISDeploymentType: 'IISWebsite'
                actionIISWebsite: 'CreateOrUpdateWebsite'
                websiteName: 'PartsUnlimited'
                websitePhysicalPath: '%SystemDrive%\inetpub\PartsUnlimited'
                websitePhysicalPathAuth: 'WebsiteWindowsAuth'
                WebsiteAuthUserName: 'canarys123'
                WebsiteAuthUserPassword: 'Password@123'
                addBinding: true
                protocol: 'http'
                iPAddress: 'All Unassigned'
                port: '82'
                bindings:
                CreateOrUpdateAppPoolForWebsite: true
                configureAuthenticationForWebsite: false
                appPoolNameForWebsite: 'PartsUnlimited'
                dotNetVersionForWebsite: 'v4.0'
                pipeLineModeForWebsite: 'Integrated'
                appPoolIdentityForWebsite: 'ApplicationPoolIdentity'
                parentWebsiteNameForVD: 'PartsUnlimited'
                virtualPathForVD:
                physicalPathForVD: '%SystemDrive%\inetpub\PartsUnlimited'
                parentWebsiteNameForApplication: 'PartsUnlimited'
                virtualPathForApplication: '%SystemDrive%\inetpub\PartsUnlimited'
                appPoolNameForApplication: 'PartsUnlimited'
                dotNetVersionForApplication: 'v4.0'
                pipeLineModeForApplication: 'Integrated'
                appPoolIdentityForApplication: 'ApplicationPoolIdentity'
                appPoolName: 'PartsUnlimited'
                dotNetVersion: 'v4.0'
                pipeLineMode: 'Integrated'
                appPoolIdentity: 'ApplicationPoolIdentity'

            
            - task: IISWebAppDeploymentOnMachineGroup@0
              displayName: 'IIS Web App Deploy'
              inputs:
                WebSiteName: 'PartsUnlimited'
                Package: '$(System.ArtifactsDirectory)\**\*.zip'
                XmlTransformation: true
                XmlVariableSubstitution: true

            - task: SqlDacpacDeploymentOnMachineGroup@0
              inputs:
                taskType: 'dacpac'
                dacpacFile: '$(System.DefaultWorkingDirectory)\**\*.dacpac'
                targetMethod: 'server'
                serverName: '$(serverName)'
                databaseName: '$(DatabaseName)'
                authScheme: 'sqlServerAuthentication'
                sqlUsername: '$(SqlUsername)'
                sqlPassword: '$(sqlPassword)'

            
- stage: Testing
  displayName: Testing
  jobs:
  - deployment: deploymentjob
    displayName: Testing Job
    environment:
      name: narayanaplayenvironment
      resourceName: seleniumvm
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
            - task: VisualStudioTestPlatformInstaller@1
              displayName: 'Visual Studio Test Platform Installer'
              inputs:
                packageFeedSelector: 'nugetOrg'
                versionSelector: 'latestStable'
            
            - task: VSTest@2
              displayName: 'Run Selenium UI tests'
              inputs:
                testSelector: 'testAssemblies'
                testAssemblyVer2: '**'
                searchFolder: '$(System.DefaultWorkingDirectory)\drop\TestAssemblies'
                resultsFolder: '$(System.DefaultWorkingDirectory)\TestResults'
                uiTests: true
                vsTestVersion: 'toolsInstaller'
                diagnosticsEnabled: true
            
            - task: PublishTestResults@2
              displayName: 'Publish Test Results *.trx'
              inputs:
                testResultsFormat: 'JUnit'
                testResultsFiles: '*.trx'
                searchFolder: '$(System.DefaultWorkingDirectory)\TestResults'
