name: PartsUnlimited.Web.buildtest

on:
  workflow_dispatch:    
  
env:
  SLN_FILE: PartsUnlimited.sln
  WEB_APP_NAME: partsplayground
  PACKAGE_TEMP_PATH: Content\D_C\a\PartsUnlimited\PartsUnlimited\src\PartsUnlimitedWebsite\obj\Release\Package\PackageTmp

jobs:
  
  Build:
    runs-on: windows-2019
    name: ⛏️ Build Web App
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
   
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1.1
      
    - name: NuGet restore
      run: nuget restore
        
    - name: Build App
      run: |
       # msbuild ${{env.SLN_FILE}} /p:TransformWebConfigEnabled=False /p:AutoParameterizationWebConfigConnectionStrings=False /p:Configuration=Release /p:Platform='Any CPU' /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true 
         msbuild ${{env.SLN_FILE}} /p:TransformWebConfigEnabled=False /p:AutoParameterizationWebConfigConnectionStrings=False /p:Configuration=Release /p:Platform='Any CPU' /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="${{github.workspace}}\stagingdir"
    
    - name: Publish Build artifact
      uses: actions/upload-artifact@v2
      with:
        name: partsunlimited
        path: ${{github.workspace}}\stagingdir
